### ISSUE TITLE
PHP version and MongoDB installation problem

### ISSUE THREAD

**Issue by hawkup** [phalcon/vagrant#7]
I checked PHP version when I ran "vagrant up". It's 5.3 version. I must to add "sudo add-apt-repository ppa:ondrej/php5" command in init.sh file for Install PHP latest version. because It can not run php5enmod.
```ruby
sudo apt-get install -y python-software-properties
sudo add-apt-repository ppa:ondrej/php5
sudo apt-get update
```
Can I use other method?
And mongoDB installation I must add -y param in script for complete installation.

**Comment by morafabio** [comment]
I've just proposed a PR: https://github.com/phalcon/vagrant/pull/8

**Comment by hawkup** [comment]
Thanks :+1:
